# Generated by Django 2.0b1 on 2017-11-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171106_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='foot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='head',
            field=models.TextField(blank=True, null=True),
        ),
    ]
