# Generated by Django 2.0b1 on 2017-11-20 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=200)),
                ('cover', models.URLField()),
                ('playcount', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('watched', models.DateTimeField()),
                ('season', models.IntegerField()),
                ('number', models.IntegerField()),
                ('tmdb', models.IntegerField()),
                ('cover', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steam_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('banner', models.URLField()),
                ('playtime', models.IntegerField()),
            ],
        ),
    ]
