version: '3'
services:
    web:
        build: site/.
        ports:
            - "5000:5000"

    worker:
        build: worker/.
    
    rabbitmq:
        image: rabbitmq

    couchdb:
        image: couchdb
