version: '3'

services:
  site:
    build: ./site
    hostname: site
    command: ./run_site.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db
      - rabbitmq
    depends_on:
      - db


  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
  
  rabbitmq:
    hostname: rabbit
    image: rabbitmq:latest
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "4369:4369"
      - "5671:5671"
      - "5672:5672"
      - "25672:25672"