version: '3'
services:
    web:
        container_name: site
        build: site/.
        ports:
            - "5000:5000"
        depends_on:
            - "couchdb"

    worker:
        container_name: worker
        build: worker/.
        command: celery -A tasks worker --beat --loglevel=info
        depends_on:
            - "rabbitmq"
            - "couchdb"
    
    rabbitmq:
        image: rabbitmq

    couchdb:
        image: couchdb
        logging:
            driver: none
