# Generated by Django 2.0 on 2017-12-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('watched', models.DateTimeField()),
                ('season', models.IntegerField()),
                ('number', models.IntegerField()),
                ('tmdb', models.IntegerField()),
                ('cover', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('watched', models.DateTimeField()),
                ('tmdb', models.IntegerField()),
                ('cover', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Episode',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
    ]
