# Generated by Django 2.0 on 2017-12-28 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20171228_2115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Episodes',
            new_name='Episode',
        ),
    ]
