# Generated by Django 2.0 on 2017-12-29 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0003_auto_20171228_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='url',
            field=models.URLField(default='http://example.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='url',
            field=models.URLField(default='http://thingisma.de'),
            preserve_default=False,
        ),
    ]
