# Generated by Django 2.0 on 2018-01-07 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0005_auto_20180107_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='year',
        ),
    ]
