# Generated by Django 2.0 on 2018-01-02 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='developer',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='fresh',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='backdrop',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='cover',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
