# Generated by Django 2.0 on 2018-01-02 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_gbid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='cover',
        ),
    ]
