# Generated by Django 2.0 on 2018-01-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_review_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='backdrop',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
