# Generated by Django 2.0.4 on 2018-04-06 10:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.URLField(default=datetime.datetime(2018, 4, 6, 22, 20, 20, 619321)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='link',
            field=models.URLField(default='hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='year',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
