# Generated by Django 2.0 on 2018-03-30 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=40, unique=True)),
                ('sfw', models.BooleanField(default=True)),
                ('text', models.TextField()),
                ('head', models.TextField(blank=True)),
                ('foot', models.TextField(blank=True)),
                ('created_at', models.DateField(auto_now=True, verbose_name='Publication date')),
                ('published_at', models.DateField(blank=True, null=True)),
                ('last_modified', models.DateField(verbose_name='Last Modified')),
                ('status', models.CharField(choices=[('D', '✍︎ Draft'), ('U', '⏏︎ Unlisted'), ('P', '✔ Published')], max_length=1)),
            ],
        ),
    ]
