# Generated by Django 2.0 on 2018-03-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now=True, verbose_name='First created'),
        ),
        migrations.AlterField(
            model_name='post',
            name='foot',
            field=models.TextField(blank=True, verbose_name='CSS/JS to include in the bottom of this post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='head',
            field=models.TextField(blank=True, verbose_name='CSS/JS to include in the <head> of this post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateField(auto_now=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sfw',
            field=models.BooleanField(default=True, verbose_name='Safe for work?'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=40, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='Post content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Post title'),
        ),
    ]
