# Generated by Django 2.0.3 on 2018-04-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_post_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Publication Date'),
        ),
    ]
